### ISSUE TITLE
Get document by ID in ControllingViewHandler

### ISSUE THREAD

**Issue by paulswithers** [jesse-gallagher/XPages-Scaffolding#1]
When creating links in a DataView, I've used entry.getNoteID() to build the document's URL rather than get the underlying document and get it's UNID. It's probably undocumented, but the documentId property also accepts Note IDs as well as UNIDs. So as a suggested enhancement for the ControllingViewHandler, I've added code the following code at line 61, if getDocumentByUNID(param.get("documentId")) returns null:

```
if (doc == null) {
    doc = database.getDocumentByID(param.get("documentId"));
}
```

**Comment by jesse-gallagher** [comment]
Done! And it only took me a year and a half!
